"""Remove tset migration (description from Category)

Revision ID: 24cdd869d2c4
Revises: 7f147209a714
Create Date: 2024-12-12 16:31:55.176778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '24cdd869d2c4'
down_revision: Union[str, None] = '7f147209a714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
